import { execFile } from 'node:child_process';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export interface GeneratedClip {
  path: string;
  buffer: Buffer;
  durationSeconds: number;
  width: number;
  height: number;
  cleanup: () => Promise<void>;
}

// The fixture is generated by FFmpeg itself rather than committed as a binary:
// the repository stays text-only and the decoder path is genuinely exercised.
export async function generateVideoClip(
  durationSeconds = 3,
  width = 320,
  height = 240,
): Promise<GeneratedClip> {
  const directory = await mkdtemp(join(tmpdir(), 'streamtube-fixture-'));
  const path = join(directory, 'clip.mp4');

  await execFileAsync('ffmpeg', [
    '-nostdin',
    '-v',
    'error',
    '-f',
    'lavfi',
    '-i',
    `testsrc=duration=${durationSeconds}:size=${width}x${height}:rate=10`,
    '-f',
    'lavfi',
    '-i',
    `sine=frequency=440:duration=${durationSeconds}`,
    '-c:v',
    'libx264',
    '-pix_fmt',
    'yuv420p',
    '-c:a',
    'aac',
    '-shortest',
    '-movflags',
    '+faststart',
    '-y',
    path,
  ]);

  return {
    path,
    buffer: await readFile(path),
    durationSeconds,
    width,
    height,
    cleanup: () => rm(directory, { recursive: true, force: true }),
  };
}
